/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jayvishaal.company.cms;

import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.ProtocolException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.net.ssl.HttpsURLConnection;
import javax.swing.JOptionPane;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 *
 * @author jayvi
 */
public class StudentManagementFrame extends javax.swing.JFrame {

    /**
     * Creates new form AttendanceMarklistFrame
     */
    public StudentManagementFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        ViewUserId4 = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        viewDetailsButton4 = new javax.swing.JButton();
        UserDeptTextBox4 = new javax.swing.JLabel();
        UserPhnoTextBox4 = new javax.swing.JLabel();
        UserNameTextBox4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        AddUserButton = new javax.swing.JButton();
        userIdAdd = new javax.swing.JTextField();
        userDeptIdAdd = new javax.swing.JTextField();
        userPasswordAdd = new javax.swing.JTextField();
        userNameAdd = new javax.swing.JTextField();
        userPhnoAdd = new javax.swing.JTextField();
        userEmailAdd = new javax.swing.JTextField();
        jTabbedPane7 = new javax.swing.JTabbedPane();
        jPanel12 = new javax.swing.JPanel();
        ViewUserId5 = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        viewDetailsButton5 = new javax.swing.JButton();
        UserDeptTextBox5 = new javax.swing.JLabel();
        UserPhnoTextBox5 = new javax.swing.JLabel();
        UserNameTextBox5 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        AddUserButton1 = new javax.swing.JButton();
        userIdAdd1 = new javax.swing.JTextField();
        userDeptIdAdd1 = new javax.swing.JTextField();
        userPasswordAdd1 = new javax.swing.JTextField();
        userNameAdd1 = new javax.swing.JTextField();
        userPhnoAdd1 = new javax.swing.JTextField();
        userEmailAdd1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 48)); // NOI18N
        jLabel2.setText("College Management System");

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\jayvi\\Downloads\\icons8-close-window-25.png")); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(32, 47, 90));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));

        jTabbedPane5.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N

        jTabbedPane6.setBackground(new java.awt.Color(32, 47, 90));
        jTabbedPane6.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N

        jPanel10.setBackground(new java.awt.Color(106, 116, 145));

        ViewUserId4.setBackground(new java.awt.Color(106, 116, 145));
        ViewUserId4.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        ViewUserId4.setForeground(new java.awt.Color(255, 255, 255));
        ViewUserId4.setBorder(null);

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText(" User Id  :");

        viewDetailsButton4.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        viewDetailsButton4.setText("View Details");
        viewDetailsButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewDetailsButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewDetailsButton4MouseClicked(evt);
            }
        });
        viewDetailsButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailsButton4ActionPerformed(evt);
            }
        });

        UserDeptTextBox4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        UserDeptTextBox4.setForeground(new java.awt.Color(255, 255, 255));

        UserPhnoTextBox4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        UserPhnoTextBox4.setForeground(new java.awt.Color(255, 255, 255));

        UserNameTextBox4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        UserNameTextBox4.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ViewUserId4, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(jSeparator8))
                        .addGap(50, 50, 50)
                        .addComponent(viewDetailsButton4))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserPhnoTextBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UserDeptTextBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UserNameTextBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 335, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ViewUserId4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(viewDetailsButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(UserNameTextBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UserDeptTextBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UserPhnoTextBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 172, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("View User", jPanel10);

        jPanel4.setBackground(new java.awt.Color(106, 116, 145));

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(" User Id  :");

        jTextField1.setBackground(new java.awt.Color(106, 116, 145));
        jTextField1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jTextField1.setBorder(null);

        jButton1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jButton1.setText("Remove User");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(jSeparator2))
                .addGap(73, 73, 73)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(248, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 314, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("Remove User", jPanel4);

        jPanel5.setBackground(new java.awt.Color(106, 116, 145));

        AddUserButton.setBackground(new java.awt.Color(255, 255, 255));
        AddUserButton.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        AddUserButton.setText("ADD");
        AddUserButton.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        AddUserButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddUserButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddUserButtonMouseEntered(evt);
            }
        });
        AddUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUserButtonActionPerformed(evt);
            }
        });

        userIdAdd.setBackground(new java.awt.Color(32, 47, 90));
        userIdAdd.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        userIdAdd.setForeground(new java.awt.Color(255, 255, 255));
        userIdAdd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userIdAdd.setToolTipText("Enter User ID");
        userIdAdd.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "StudentID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        userIdAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userIdAddActionPerformed(evt);
            }
        });

        userDeptIdAdd.setBackground(new java.awt.Color(32, 47, 90));
        userDeptIdAdd.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        userDeptIdAdd.setForeground(new java.awt.Color(255, 255, 255));
        userDeptIdAdd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userDeptIdAdd.setToolTipText("Enter User Dept ID");
        userDeptIdAdd.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Class ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        userDeptIdAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userDeptIdAddActionPerformed(evt);
            }
        });

        userPasswordAdd.setBackground(new java.awt.Color(32, 47, 90));
        userPasswordAdd.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        userPasswordAdd.setForeground(new java.awt.Color(255, 255, 255));
        userPasswordAdd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userPasswordAdd.setToolTipText("Enter User Password");
        userPasswordAdd.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        userPasswordAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userPasswordAddActionPerformed(evt);
            }
        });

        userNameAdd.setBackground(new java.awt.Color(32, 47, 90));
        userNameAdd.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        userNameAdd.setForeground(new java.awt.Color(255, 255, 255));
        userNameAdd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userNameAdd.setToolTipText("Enter User name");
        userNameAdd.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Student  Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        userNameAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameAddActionPerformed(evt);
            }
        });

        userPhnoAdd.setBackground(new java.awt.Color(32, 47, 90));
        userPhnoAdd.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        userPhnoAdd.setForeground(new java.awt.Color(255, 255, 255));
        userPhnoAdd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userPhnoAdd.setToolTipText("Enter User Phno");
        userPhnoAdd.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Phone Number", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        userPhnoAdd.setCaretColor(new java.awt.Color(255, 255, 255));
        userPhnoAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userPhnoAddActionPerformed(evt);
            }
        });

        userEmailAdd.setBackground(new java.awt.Color(32, 47, 90));
        userEmailAdd.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        userEmailAdd.setForeground(new java.awt.Color(255, 255, 255));
        userEmailAdd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userEmailAdd.setToolTipText("Enter User Email");
        userEmailAdd.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E-mail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        userEmailAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userEmailAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userDeptIdAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userIdAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userEmailAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userNameAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userPhnoAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userPasswordAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(121, 121, 121))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addComponent(AddUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userIdAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameAdd))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userPasswordAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userDeptIdAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userPhnoAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userEmailAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(AddUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jTabbedPane6.addTab("Add User", jPanel5);

        jTabbedPane5.addTab("Manage Students", jTabbedPane6);

        jTabbedPane7.setBackground(new java.awt.Color(32, 47, 90));
        jTabbedPane7.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N

        jPanel12.setBackground(new java.awt.Color(106, 116, 145));

        ViewUserId5.setBackground(new java.awt.Color(106, 116, 145));
        ViewUserId5.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        ViewUserId5.setForeground(new java.awt.Color(255, 255, 255));
        ViewUserId5.setBorder(null);

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText(" User Id  :");

        viewDetailsButton5.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        viewDetailsButton5.setText("View Details");
        viewDetailsButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewDetailsButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewDetailsButton5MouseClicked(evt);
            }
        });
        viewDetailsButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailsButton5ActionPerformed(evt);
            }
        });

        UserDeptTextBox5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        UserDeptTextBox5.setForeground(new java.awt.Color(255, 255, 255));

        UserPhnoTextBox5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        UserPhnoTextBox5.setForeground(new java.awt.Color(255, 255, 255));

        UserNameTextBox5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        UserNameTextBox5.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ViewUserId5, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(jSeparator9))
                        .addGap(18, 18, 18)
                        .addComponent(viewDetailsButton5))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserPhnoTextBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UserDeptTextBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UserNameTextBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 367, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(viewDetailsButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel12Layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel12Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(ViewUserId5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(UserNameTextBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UserDeptTextBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UserPhnoTextBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 172, Short.MAX_VALUE))
        );

        jTabbedPane7.addTab("View User", jPanel12);

        jPanel13.setBackground(new java.awt.Color(106, 116, 145));

        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText(" User Id  :");

        jTextField2.setBackground(new java.awt.Color(106, 116, 145));
        jTextField2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jTextField2.setBorder(null);

        jButton2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jButton2.setText("Remove User");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(jSeparator3))
                .addGap(100, 100, 100)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(221, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel13Layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel13Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 314, Short.MAX_VALUE))
        );

        jTabbedPane7.addTab("Remove User", jPanel13);

        jPanel14.setBackground(new java.awt.Color(106, 116, 145));

        AddUserButton1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        AddUserButton1.setText("ADD");
        AddUserButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AddUserButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddUserButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddUserButton1MouseEntered(evt);
            }
        });
        AddUserButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUserButton1ActionPerformed(evt);
            }
        });

        userIdAdd1.setBackground(new java.awt.Color(204, 204, 204));
        userIdAdd1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        userIdAdd1.setForeground(new java.awt.Color(255, 255, 255));
        userIdAdd1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userIdAdd1.setToolTipText("Enter User ID");
        userIdAdd1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ProfessorID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 1, 14))); // NOI18N
        userIdAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userIdAdd1ActionPerformed(evt);
            }
        });

        userDeptIdAdd1.setBackground(new java.awt.Color(204, 204, 204));
        userDeptIdAdd1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        userDeptIdAdd1.setForeground(new java.awt.Color(255, 255, 255));
        userDeptIdAdd1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userDeptIdAdd1.setToolTipText("Enter User Dept ID");
        userDeptIdAdd1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dept ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 1, 14))); // NOI18N
        userDeptIdAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userDeptIdAdd1ActionPerformed(evt);
            }
        });

        userPasswordAdd1.setBackground(new java.awt.Color(204, 204, 204));
        userPasswordAdd1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        userPasswordAdd1.setForeground(new java.awt.Color(255, 255, 255));
        userPasswordAdd1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userPasswordAdd1.setToolTipText("Enter User Password");
        userPasswordAdd1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 1, 14))); // NOI18N
        userPasswordAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userPasswordAdd1ActionPerformed(evt);
            }
        });

        userNameAdd1.setBackground(new java.awt.Color(204, 204, 204));
        userNameAdd1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        userNameAdd1.setForeground(new java.awt.Color(255, 255, 255));
        userNameAdd1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userNameAdd1.setToolTipText("Enter User name");
        userNameAdd1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Professor Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 1, 14))); // NOI18N
        userNameAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameAdd1ActionPerformed(evt);
            }
        });

        userPhnoAdd1.setBackground(new java.awt.Color(204, 204, 204));
        userPhnoAdd1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        userPhnoAdd1.setForeground(new java.awt.Color(255, 255, 255));
        userPhnoAdd1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userPhnoAdd1.setToolTipText("Enter User Phno");
        userPhnoAdd1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Phone Number", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 1, 14))); // NOI18N
        userPhnoAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userPhnoAdd1ActionPerformed(evt);
            }
        });

        userEmailAdd1.setBackground(new java.awt.Color(204, 204, 204));
        userEmailAdd1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        userEmailAdd1.setForeground(new java.awt.Color(255, 255, 255));
        userEmailAdd1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userEmailAdd1.setToolTipText("Enter User Email");
        userEmailAdd1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "E-mail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 1, 14))); // NOI18N
        userEmailAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userEmailAdd1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddUserButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(318, 318, 318))
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userEmailAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userIdAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userDeptIdAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addComponent(userPhnoAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userNameAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userPasswordAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(88, 88, 88))))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userIdAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameAdd1))
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userDeptIdAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userPasswordAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userEmailAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userPhnoAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(AddUserButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane7.addTab("Add User", jPanel14);

        jTabbedPane5.addTab("Manage Users", jTabbedPane7);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(21, 21, 21))
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(0, 18, 51));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\jayvi\\Downloads\\icons8-book-40.png")); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\jayvi\\Downloads\\icons8-exam-25.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void userEmailAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userEmailAdd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userEmailAdd1ActionPerformed

    private void userPhnoAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userPhnoAdd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userPhnoAdd1ActionPerformed

    private void userNameAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameAdd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameAdd1ActionPerformed

    private void userPasswordAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userPasswordAdd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userPasswordAdd1ActionPerformed

    private void userDeptIdAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userDeptIdAdd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userDeptIdAdd1ActionPerformed

    private void userIdAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userIdAdd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userIdAdd1ActionPerformed

    private void AddUserButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUserButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddUserButton1ActionPerformed

    private void AddUserButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddUserButton1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_AddUserButton1MouseEntered

    private void AddUserButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddUserButton1MouseClicked
        String UserId = userIdAdd.getText().toString();
        String UserName = userNameAdd.getText().toString();
        String UserDept = userDeptIdAdd.getText().toString();
        String UserPassword = userPasswordAdd.getText().toString();
        String UserEmail    = userEmailAdd.getText().toString();
        String UserPhno     =  userPhnoAdd.getText().toString();

        try {
            // TODO add your handling code here:

            String url = "https://cms-ooad.herokuapp.com/api/Professor/createUser";
            URL obj = new URL(url);
            HttpsURLConnection con = (HttpsURLConnection) obj.openConnection();

            //add reuqest header
            con.setRequestMethod("POST");
            con.setRequestProperty("User-Agent", "Mozilla/5.0");
            con.setRequestProperty("Accept-Language", "en-US,en;q=0.5");

            String urlParameters = "deptId="+UserDept+"&professorId="+UserId+"&professorName="+UserName+"&password="+UserPassword+"&professorPno="+UserPhno+"&professorEmail="+UserEmail+"&classHandling=[]";

            // Send post request
            con.setDoOutput(true);
            DataOutputStream wr = new DataOutputStream(con.getOutputStream());
            wr.writeBytes(urlParameters);
            wr.flush();
            wr.close();

            int responseCode = con.getResponseCode();
            System.out.println("\nSending 'POST' request to URL : " + url);
            System.out.println("Post parameters : " + urlParameters);
            System.out.println("Response Code : " + responseCode);

            BufferedReader in = new BufferedReader(
                new InputStreamReader(con.getInputStream()));
            String inputLine;
            StringBuffer response = new StringBuffer();

            while ((inputLine = in.readLine()) != null) {
                response.append(inputLine);
            }
            in.close();

            //print result
            System.out.println(response.toString());
            if(responseCode == 200){
                JOptionPane.showMessageDialog(StudentManagementFrame.this, "Sucessfully Record Added");

                userDeptIdAdd.setText("");
                userEmailAdd.setText("");
                userIdAdd.setText("");
                userNameAdd.setText("");
                userPasswordAdd.setText("");
                userPhnoAdd.setText("");

            }
            else
            {
                JOptionPane.showMessageDialog(StudentManagementFrame.this, "Something Went Wrong :( !!! Record  Not Added");
            }
        } catch (MalformedURLException ex) {
            Logger.getLogger(LMSFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ProtocolException ex) {
            Logger.getLogger(LMSFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(LMSFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AddUserButton1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void viewDetailsButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailsButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewDetailsButton5ActionPerformed

    private void viewDetailsButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewDetailsButton5MouseClicked
        // TODO add your handling code here:
        String UserId = ViewUserId5.getText().toString();
        UserDeptTextBox5.setText("");
        UserNameTextBox5.setText("");
        UserPhnoTextBox5.setText("");
        try {

            // TODO add your handling code here:
            //Search By Genre
            String api_url = "https://cms-ooad.herokuapp.com/api/Professor/"+UserId;
            URL obj = new URL(api_url);
            HttpsURLConnection conn1 = (HttpsURLConnection) obj.openConnection();
            conn1.setRequestMethod("GET");
            conn1.setRequestProperty("User-Agent", "Mozilla/5.0");

            int responseCode = conn1.getResponseCode();
            System.out.println("\nSending 'GET' request to URL : " + api_url);
            System.out.println("Response Code : " + responseCode);
            BufferedReader in = new BufferedReader(
                new InputStreamReader(conn1.getInputStream()));
            String inputLine;
            StringBuffer response = new StringBuffer();
            while ((inputLine = in.readLine()) != null) {
                response.append(inputLine);
            }
            in.close();
            //print in String
            System.out.println(response.toString());
            //Read JSON response and print
            JSONParser parser = new JSONParser();
            JSONObject userObj = (JSONObject) parser.parse(response.toString());
            UserNameTextBox5.setText("Professor Name : "+userObj.get("professorName").toString());
            UserDeptTextBox5.setText("Dept           : "+userObj.get("deptId").toString());
            UserPhnoTextBox5.setText("Professor Phno : "+userObj.get("professorPno").toString());

        }catch (MalformedURLException ex) {
            Logger.getLogger(LibraryFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(LibraryFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(LibraryFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_viewDetailsButton5MouseClicked

    private void userEmailAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userEmailAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userEmailAddActionPerformed

    private void userPhnoAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userPhnoAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userPhnoAddActionPerformed

    private void userNameAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameAddActionPerformed

    private void userPasswordAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userPasswordAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userPasswordAddActionPerformed

    private void userDeptIdAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userDeptIdAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userDeptIdAddActionPerformed

    private void userIdAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userIdAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userIdAddActionPerformed

    private void AddUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUserButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddUserButtonActionPerformed

    private void AddUserButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddUserButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_AddUserButtonMouseEntered

    private void AddUserButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddUserButtonMouseClicked
        String UserId = userIdAdd.getText().toString();
        String UserName = userNameAdd.getText().toString();
        String UserDept = userDeptIdAdd.getText().toString();//classId
        String UserPassword = userPasswordAdd.getText().toString();
        String UserEmail    = userEmailAdd.getText().toString();
        String UserPhno     =  userPhnoAdd.getText().toString();

        try {
            // TODO add your handling code here:

            String url = "https://cms-ooad.herokuapp.com/api/Student/createUser";
            URL obj = new URL(url);
            HttpsURLConnection con = (HttpsURLConnection) obj.openConnection();

            //add reuqest header
            con.setRequestMethod("POST");
            con.setRequestProperty("User-Agent", "Mozilla/5.0");
            con.setRequestProperty("Accept-Language", "en-US,en;q=0.5");

            String urlParameters = "classId="+UserDept+"&studentId="+UserId+"&studentName="+UserName+"&password="+UserPassword+"&parentPno="+UserPhno+"&parentEmail="+UserEmail+"&libraryInfo=[]&bookBorrowed=0";

            // Send post request
            con.setDoOutput(true);
            DataOutputStream wr = new DataOutputStream(con.getOutputStream());
            wr.writeBytes(urlParameters);
            wr.flush();
            wr.close();

            int responseCode = con.getResponseCode();
            System.out.println("\nSending 'POST' request to URL : " + url);
            System.out.println("Post parameters : " + urlParameters);
            System.out.println("Response Code : " + responseCode);

            BufferedReader in = new BufferedReader(
                new InputStreamReader(con.getInputStream()));
            String inputLine;
            StringBuffer response = new StringBuffer();

            while ((inputLine = in.readLine()) != null) {
                response.append(inputLine);
            }
            in.close();

            //print result
            System.out.println(response.toString());
            if(responseCode == 200){
                JOptionPane.showMessageDialog(StudentManagementFrame.this, "Sucessfully Record Added");

                userDeptIdAdd.setText("");
                userEmailAdd.setText("");
                userIdAdd.setText("");
                userNameAdd.setText("");
                userPasswordAdd.setText("");
                userPhnoAdd.setText("");

            }
            else
            {
                JOptionPane.showMessageDialog(StudentManagementFrame.this, "Something Went Wrong :( !!! Record  Not Added");
            }
        } catch (MalformedURLException ex) {
            Logger.getLogger(LMSFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ProtocolException ex) {
            Logger.getLogger(LMSFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(LMSFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AddUserButtonMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void viewDetailsButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailsButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewDetailsButton4ActionPerformed

    private void viewDetailsButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewDetailsButton4MouseClicked
        // TODO add your handling code here:
        String UserId = ViewUserId4.getText().toString();
        UserDeptTextBox4.setText("");
        UserNameTextBox4.setText("");
        UserPhnoTextBox4.setText("");
        try {

            // TODO add your handling code here:
            //Search By Genre
            String api_url = "https://cms-ooad.herokuapp.com/api/Student/"+UserId;
            URL obj = new URL(api_url);
            HttpsURLConnection conn1 = (HttpsURLConnection) obj.openConnection();
            conn1.setRequestMethod("GET");
            conn1.setRequestProperty("User-Agent", "Mozilla/5.0");

            int responseCode = conn1.getResponseCode();
            System.out.println("\nSending 'GET' request to URL : " + api_url);
            System.out.println("Response Code : " + responseCode);
            BufferedReader in = new BufferedReader(
                new InputStreamReader(conn1.getInputStream()));
            String inputLine;
            StringBuffer response = new StringBuffer();
            while ((inputLine = in.readLine()) != null) {
                response.append(inputLine);
            }
            in.close();
            //print in String
            System.out.println(response.toString());
            //Read JSON response and print
            JSONParser parser = new JSONParser();
            JSONObject userObj = (JSONObject) parser.parse(response.toString());
            UserNameTextBox4.setText("Student Name : "+userObj.get("studentName").toString());
            UserDeptTextBox4.setText("Dept           : "+userObj.get("classId").toString());
            UserPhnoTextBox4.setText("Parent Phno : "+userObj.get("parentPno").toString());

        }catch (MalformedURLException ex) {
            Logger.getLogger(LibraryFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(LibraryFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(LibraryFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_viewDetailsButton4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        new HomeFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentManagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentManagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentManagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentManagementFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentManagementFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddUserButton;
    private javax.swing.JButton AddUserButton1;
    private javax.swing.JTabbedPane MainTab;
    private javax.swing.JTabbedPane MainTab1;
    private javax.swing.JTabbedPane MainTab2;
    private javax.swing.JTabbedPane MainTab3;
    private javax.swing.JLabel UserDeptTextBox;
    private javax.swing.JLabel UserDeptTextBox1;
    private javax.swing.JLabel UserDeptTextBox2;
    private javax.swing.JLabel UserDeptTextBox3;
    private javax.swing.JLabel UserDeptTextBox4;
    private javax.swing.JLabel UserDeptTextBox5;
    private javax.swing.JLabel UserNameTextBox;
    private javax.swing.JLabel UserNameTextBox1;
    private javax.swing.JLabel UserNameTextBox2;
    private javax.swing.JLabel UserNameTextBox3;
    private javax.swing.JLabel UserNameTextBox4;
    private javax.swing.JLabel UserNameTextBox5;
    private javax.swing.JLabel UserPhnoTextBox;
    private javax.swing.JLabel UserPhnoTextBox1;
    private javax.swing.JLabel UserPhnoTextBox2;
    private javax.swing.JLabel UserPhnoTextBox3;
    private javax.swing.JLabel UserPhnoTextBox4;
    private javax.swing.JLabel UserPhnoTextBox5;
    private javax.swing.JTextField ViewUserId;
    private javax.swing.JTextField ViewUserId1;
    private javax.swing.JTextField ViewUserId2;
    private javax.swing.JTextField ViewUserId3;
    private javax.swing.JTextField ViewUserId4;
    private javax.swing.JTextField ViewUserId5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTabbedPane jTabbedPane7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField userDeptIdAdd;
    private javax.swing.JTextField userDeptIdAdd1;
    private javax.swing.JTextField userEmailAdd;
    private javax.swing.JTextField userEmailAdd1;
    private javax.swing.JTextField userIdAdd;
    private javax.swing.JTextField userIdAdd1;
    private javax.swing.JTextField userNameAdd;
    private javax.swing.JTextField userNameAdd1;
    private javax.swing.JTextField userPasswordAdd;
    private javax.swing.JTextField userPasswordAdd1;
    private javax.swing.JTextField userPhnoAdd;
    private javax.swing.JTextField userPhnoAdd1;
    private javax.swing.JButton viewDetailsButton;
    private javax.swing.JButton viewDetailsButton1;
    private javax.swing.JButton viewDetailsButton2;
    private javax.swing.JButton viewDetailsButton3;
    private javax.swing.JButton viewDetailsButton4;
    private javax.swing.JButton viewDetailsButton5;
    // End of variables declaration//GEN-END:variables
}
